apiVersion: v1
kind: Service
metadata:
  name: memories
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memories
  ports:
    - name: dapr-http
      port: 80
      targetPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: memories-mcp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memories-mcp
  ports:
    - name: dapr-http
      port: 80
      targetPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: memories-access-telemetry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memories-access-telemetry
  ports:
    - name: dapr-http
      port: 80
      targetPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: memories-access-telemetry-clock
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memories-access-telemetry-clock
  ports:
    - name: dapr-http
      port: 80
      targetPort: 3500
