apiVersion: v1
kind: Namespace
metadata:
  name: openbao
  labels:
    kubernetes.io/metadata.name: openbao
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    hexalith.io/platform-owner: jpiquot
    hexalith.io/security-reviewer: murat-tea-for-jpiquot
