apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    # Expected volume mount: Kubernetes Secret or projected volume at /etc/dapr/secrets.
    - name: secretsFile
      value: "/etc/dapr/secrets/secrets.json"
    - name: nestedSeparator
      value: ":"
