apiVersion: builtin
kind: PatchTransformer
metadata:
  name: qualification-dapr-role-binding-namespace
patch: |-
  - op: replace
    path: /metadata/namespace
    value: dapr-system
target:
  group: rbac.authorization.k8s.io
  version: v1
  kind: RoleBinding
  name: access-telemetry-qualification-dapr-control-plane
