<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
    <UserSecretsId>hexalith-memories</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexalith.Memories.Mcp\Hexalith.Memories.Mcp.csproj" />
    <ProjectReference Include="..\Hexalith.Memories.Server\Hexalith.Memories.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" />
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
