<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexalith.Memories.Contracts\Hexalith.Memories.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NRedisStack" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="NFalkorDB" />
  </ItemGroup>

</Project>
