apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hexalith-memories
resources:
  - namespace.yaml
  - ../../base
images:
  - name: registry.hexalith.com/memories
    newName: registry.hexalith.com/memories
    newTag: 0.0.0
  - name: registry.hexalith.com/memories-mcp
    newName: registry.hexalith.com/memories-mcp
    newTag: 0.0.0
