<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hexalith.Memories.Server.Tests" />
    <InternalsVisibleTo Include="Hexalith.Memories.Benchmarks" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexalith.Memories.Contracts\Hexalith.Memories.Contracts.csproj" />
    <ProjectReference Include="..\Hexalith.Memories.Redis\Hexalith.Memories.Redis.csproj" />
    <ProjectReference
      Include="..\Hexalith.Memories.ServiceDefaults\Hexalith.Memories.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ByteAether.Ulid" />
    <PackageReference Include="Dapr.AspNetCore" />
    <PackageReference Include="Dapr.Client" />
    <PackageReference Include="Dapr.Workflow" />
    <PackageReference Include="Dapr.Actors" />
    <PackageReference Include="Dapr.Actors.AspNetCore" />
    <PackageReference Include="Dapr.AI" />
    <PackageReference Include="Dapr.AI.Microsoft.Extensions" />
    <PackageReference Include="Kreuzberg" />
  </ItemGroup>

</Project>