// <copyright file="MemoriesJsonContext.cs" company="ITANEO">
// Copyright (c) ITANEO (https://www.itaneo.com). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Hexalith.Memories.Contracts.V1;

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

/// <summary>Source-generated JSON metadata for commonly exchanged Memories contracts.</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(AddCaseMemberInput))]
[JsonSerializable(typeof(CreateAnnotationInput))]
[JsonSerializable(typeof(List<MemoryUnit>))]
[JsonSerializable(typeof(Case))]
[JsonSerializable(typeof(CaseActivityEvent))]
[JsonSerializable(typeof(CaseGroupSummary))]
[JsonSerializable(typeof(CaseActivityEventType))]
[JsonSerializable(typeof(CaseActivityInput))]
[JsonSerializable(typeof(CaseMember))]
[JsonSerializable(typeof(CaseMemberType))]
[JsonSerializable(typeof(CaseStatus))]
[JsonSerializable(typeof(CaseStatusDetail))]
[JsonSerializable(typeof(CreateCaseInput))]
[JsonSerializable(typeof(List<Case>))]
[JsonSerializable(typeof(List<CaseActivityEvent>))]
[JsonSerializable(typeof(List<CaseGroupSummary>))]
[JsonSerializable(typeof(List<CaseMember>))]
[JsonSerializable(typeof(AxisExplanation))]
[JsonSerializable(typeof(Dictionary<string, AxisExplanation>))]
[JsonSerializable(typeof(Dictionary<string, MetadataField>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(ConfidencePromotionRequest))]
[JsonSerializable(typeof(ConfidencePromotionResult))]
[JsonSerializable(typeof(EdgeTypeCategory))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(EvidencePacket))]
[JsonSerializable(typeof(EvidencePacketAxisEvidence))]
[JsonSerializable(typeof(EvidencePacketEvidence))]
[JsonSerializable(typeof(EvidencePacketEvidenceStrength))]
[JsonSerializable(typeof(EvidencePacketExpansionHandle))]
[JsonSerializable(typeof(EvidencePacketGraphSummary))]
[JsonSerializable(typeof(EvidencePacketIsolationStatus))]
[JsonSerializable(typeof(EvidencePacketOmittedDetails))]
[JsonSerializable(typeof(EvidencePacketOmissionReason))]
[JsonSerializable(typeof(EvidencePacketRecoveryAction))]
[JsonSerializable(typeof(EvidencePacketRecoveryKind))]
[JsonSerializable(typeof(EvidencePacketResultSummary))]
[JsonSerializable(typeof(EvidencePacketScope))]
[JsonSerializable(typeof(EvidencePacketSource))]
[JsonSerializable(typeof(EvidencePacketState))]
[JsonSerializable(typeof(IReadOnlyList<EvidencePacketAxisEvidence>))]
[JsonSerializable(typeof(IReadOnlyList<EvidencePacketExpansionHandle>))]
[JsonSerializable(typeof(IReadOnlyList<EvidencePacketRecoveryAction>))]
[JsonSerializable(typeof(IReadOnlyList<EvidencePacketSource>))]
[JsonSerializable(typeof(ExtractionInput))]
[JsonSerializable(typeof(FusedScoredResult))]
[JsonSerializable(typeof(FusionWeights))]
[JsonSerializable(typeof(HybridSearchResult))]
[JsonSerializable(typeof(OmittedReason))]
[JsonSerializable(typeof(ExtractionResult))]
[JsonSerializable(typeof(FailureDetails))]
[JsonSerializable(typeof(GraphEdge))]
[JsonSerializable(typeof(IReadOnlyList<ScoredResult>))]
[JsonSerializable(typeof(IndexInput))]
[JsonSerializable(typeof(IndexResult))]
[JsonSerializable(typeof(IngestionInput))]
[JsonSerializable(typeof(IngestionResult))]
[JsonSerializable(typeof(IngestionWorkflowStatus))]
[JsonSerializable(typeof(MemoryUnit))]
[JsonSerializable(typeof(MemoryUnitIdLookupResponse))]
[JsonSerializable(typeof(MetadataField))]
[JsonSerializable(typeof(ScoredResult))]
[JsonSerializable(typeof(SearchExplanation))]
[JsonSerializable(typeof(SearchQuery))]
[JsonSerializable(typeof(SearchResult))]
[JsonSerializable(typeof(TenantEmbeddingConfig))]
[JsonSerializable(typeof(TraversalNode))]
[JsonSerializable(typeof(TraversalEdgeInfo))]
[JsonSerializable(typeof(TraversalGapMarker))]
[JsonSerializable(typeof(IReadOnlyList<TraversalGapMarker>))]
[JsonSerializable(typeof(TraversalResult))]
[JsonSerializable(typeof(IReadOnlyList<TraversalNode>))]
[JsonSerializable(typeof(TenantStatus))]
[JsonSerializable(typeof(TenantInfo))]
[JsonSerializable(typeof(TenantProvisioningInput))]
[JsonSerializable(typeof(TenantProvisioningResult))]
[JsonSerializable(typeof(TenantStatusUpdateInput))]
[JsonSerializable(typeof(TenantDeletionInput))]
[JsonSerializable(typeof(TenantDeletionResult))]
[JsonSerializable(typeof(BatchedGraphDeletionInput))]
[JsonSerializable(typeof(BatchedGraphDeletionResult))]
[JsonSerializable(typeof(IReadOnlyList<TenantInfo>))]
[JsonSerializable(typeof(TenantIsolationCheckResult))]
[JsonSerializable(typeof(TenantIsolationVerificationResult))]
// Story 5.5: tenant configuration & listing contracts.
[JsonSerializable(typeof(TenantSummary))]
[JsonSerializable(typeof(IReadOnlyList<TenantSummary>))]
[JsonSerializable(typeof(List<TenantSummary>))]
[JsonSerializable(typeof(TenantIndexSizes))]
[JsonSerializable(typeof(TenantIndexStatus))]
[JsonSerializable(typeof(IndexHealth))]
[JsonSerializable(typeof(TenantConfigurationView))]
[JsonSerializable(typeof(TenantUpdateInput))]
// Story 6.3: retry / failure visibility / re-ingestion contracts.
[JsonSerializable(typeof(CaseIngestionCounts))]
[JsonSerializable(typeof(CounterTransitionInput))]
[JsonSerializable(typeof(FailedUnitInput))]
[JsonSerializable(typeof(FailedUnitSummary))]
[JsonSerializable(typeof(FailedUnitsPage))]
[JsonSerializable(typeof(IReadOnlyList<FailedUnitSummary>))]
[JsonSerializable(typeof(ReIngestRequest))]
[JsonSerializable(typeof(ReIngestedUnitInfo))]
[JsonSerializable(typeof(BulkReIngestionResponse))]
[JsonSerializable(typeof(IReadOnlyList<ReIngestedUnitInfo>))]
// Story 6.1: URL and directory ingestion contracts.
[JsonSerializable(typeof(UrlFetchResult))]
[JsonSerializable(typeof(FetchUrlInput))]
[JsonSerializable(typeof(UrlIngestionRequest))]
[JsonSerializable(typeof(UrlIngestionResponse))]
[JsonSerializable(typeof(DirectoryIngestionRequest))]
[JsonSerializable(typeof(DirectoryIngestionOutcome))]
[JsonSerializable(typeof(SkippedFile))]
[JsonSerializable(typeof(IReadOnlyList<SkippedFile>))]
[JsonSerializable(typeof(BatchStatusResponse))]
[JsonSerializable(typeof(BatchStatusCounts))]
[JsonSerializable(typeof(BatchInstanceStatus))]
[JsonSerializable(typeof(IReadOnlyList<BatchInstanceStatus>))]
// Story 7.5: access telemetry + summary contracts.
[JsonSerializable(typeof(AccessTelemetryEvent))]
[JsonSerializable(typeof(TelemetrySummary))]
[JsonSerializable(typeof(TelemetryIndexSizes))]
[JsonSerializable(typeof(TelemetryIndexHealth))]
[JsonSerializable(typeof(TelemetrySearchMetrics))]
[JsonSerializable(typeof(TelemetryAxisCounters))]
[JsonSerializable(typeof(TelemetryIngestionMetrics))]
// Story 8.2: consistency verification + repair contracts.
[JsonSerializable(typeof(ConsistencyRepairRecommendation))]
[JsonSerializable(typeof(ConsistencyVerificationRequest))]
[JsonSerializable(typeof(ConsistencyDiscrepancy))]
[JsonSerializable(typeof(IReadOnlyList<ConsistencyDiscrepancy>))]
[JsonSerializable(typeof(ConsistencyVerificationResult))]
[JsonSerializable(typeof(ConsistencyVerificationStatus))]
[JsonSerializable(typeof(ConsistencySyntacticDetail))]
[JsonSerializable(typeof(ConsistencySemanticDetail))]
[JsonSerializable(typeof(ConsistencyGraphDetail))]
[JsonSerializable(typeof(ConsistencyInspectionResult))]
[JsonSerializable(typeof(ConsistencyWorkflowProgress))]
[JsonSerializable(typeof(ConsistencyRepairRequest))]
[JsonSerializable(typeof(RepairActionRecord))]
[JsonSerializable(typeof(IReadOnlyList<RepairActionRecord>))]
[JsonSerializable(typeof(ConsistencyRepairResult))]
[JsonSerializable(typeof(ConsistencyRepairStatus))]
[JsonSerializable(typeof(ConsistencyWorkflowState))]
// Story 8.3: data export envelope contracts.
[JsonSerializable(typeof(ExportManifest))]
[JsonSerializable(typeof(ExportScope))]
[JsonSerializable(typeof(ExportStatistics))]
[JsonSerializable(typeof(ExportedEdge))]
[JsonSerializable(typeof(ExportedTenantConfig))]
[JsonSerializable(typeof(ExportedMemoryUnit))]
// Story 9.2: dual embedding + NL description contracts.
[JsonSerializable(typeof(ConfidenceSource))]
[JsonSerializable(typeof(EmbeddingContentKind))]
[JsonSerializable(typeof(NaturalLanguageDescriptionInput))]
[JsonSerializable(typeof(NaturalLanguageDescriptionResult))]
[JsonSerializable(typeof(NaturalLanguageIndexInput))]
[JsonSerializable(typeof(NaturalLanguageEmbeddingStatus))]
[JsonSerializable(typeof(QueueNaturalLanguageEmbeddingRetryInput))]
[JsonSerializable(typeof(FailedNaturalLanguageEmbeddingRecord))]
[JsonSerializable(typeof(NaturalLanguageEmbeddingRetryInput))]
[JsonSerializable(typeof(NaturalLanguageEmbeddingRetryResult))]
// Story 9.2 Review D7: typed identifier for informational consistency notes.
[JsonSerializable(typeof(ConsistencyNoteKind))]
// Story 9.3: handler registry + mismatch report contracts.
[JsonSerializable(typeof(HandlerRegistrationSnapshot))]
[JsonSerializable(typeof(HandlerRegistration))]
[JsonSerializable(typeof(ObservedEventTypeSummary))]
[JsonSerializable(typeof(IReadOnlyList<HandlerRegistration>))]
[JsonSerializable(typeof(IReadOnlyList<ObservedEventTypeSummary>))]
[JsonSerializable(typeof(HandlerSubscriptionStatus))]
[JsonSerializable(typeof(HandlerMismatchReport))]
[JsonSerializable(typeof(HandlerMismatchReportSummary))]
[JsonSerializable(typeof(HandlerMismatch))]
[JsonSerializable(typeof(IReadOnlyList<HandlerMismatch>))]
[JsonSerializable(typeof(HandlerMismatchCategory))]
[JsonSerializable(typeof(HandlerMismatchSeverity))]
[JsonSerializable(typeof(SearchIndexEntryChanged))]
[JsonSerializable(typeof(SearchIndexEntryRemoved))]
internal sealed partial class MemoriesJsonSourceGenerationContext : JsonSerializerContext;

/// <summary>Shared JSON serialization options for all Memories contracts.</summary>
public static class MemoriesJsonContext
{
    /// <summary>Gets the shared serializer options for Memories contracts and workflow payloads.</summary>
    public static JsonSerializerOptions Options { get; } = CreateOptions();

    private static JsonSerializerOptions CreateOptions()
        => new(JsonSerializerDefaults.Web)
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            TypeInfoResolver = JsonTypeInfoResolver.Combine(
                MemoriesJsonSourceGenerationContext.Default,
                new DefaultJsonTypeInfoResolver()),
        };
}
