namespace Hexalith.Memories.Contracts.V1;

using System.Text.Json.Serialization;

/// <summary>Indicates whether metadata was supplied by a human or generated by AI.</summary>
[JsonConverter(typeof(CamelCaseStringEnumConverter<MetadataOrigin>))]
public enum MetadataOrigin
{
    Human,
    Ai,
}
